### PR TITLE
Check dead links

### PR DESCRIPTION
**Pull request by p2635**
Dead links to check:
[✖] https://www.google.com/intl/zh-CN/ime/pinyin/ **Is this old/discontinued? [R]**
[✖] https://pinyin.sogou.com/ - false positive, ignore this
[✖] http://www.freehongkong.net/learn-cantonese-grammar-conjunction-and-sentence-connector/ **Old link - replaced with web archive link for now [R]**
[✖] http://www.isimplylovelanguages.com/serial-how-to-use-anki-effectively/ **The website is in German? Makes it even harder for me to track down the original post [R]**
[✖] https://addons.mozilla.org/en-us/firefox/addon/meihua-chinese-converter/ There seems to be no activity since 2017 and I can't find it the addon anymore - removed for now
[✖] http://traslate.google.com/ - simply a typo, I have corrected it now
[✖] http://www.perapera.org/  - false positive, ignore this
[✖] http://news.singtao.ca/toronto/ - corrected
[✖] https://vndb.org/v/all?q=&fil=olang-zh&rfil= **[R] broken, website doesn't work either, can we remove?**
[✖] https://vndb.org/v/all?q=&fil=lang-zh&rfil= **[R] broken, website doesn't work either, can we remove?**
[✖] http://dramatvb.com/ - **[R] corrected, it redirects to https://www.tvbanywhere.com/. Just selling a product, is it still beneficial to keep?**
[✖] https://mandarinmadeez.com/ **[R] is it this one? https://www.youtube.com/user/aCUPofTEAwithFI/about**
[✖] http://singchinesesongs.com/ **[R] broken, please review**
[✖] http://radio.bbtv.cn/ **[R] can't find it**
[✖] http://web3.hakka.gov.tw/lp.asp?ctNode=2355&amp;CtUnit=760&amp;BaseDSD=7&amp;mp=11&amp;ps= **[R] loads forever**
[✖] http://open-lit.com/list.php  - false positive, ignore this

### CODE REVIEW

**Comment by p2635** [comment]
Is the Google Input (Windows) old?

**Comment by p2635** [comment]
If I put [R], I would like you to review, thanks!

**Comment by p2635** [comment]
I've done what I can, over to you to check!

**Comment by espaspw** [comment]
I've merged in the existing changes. Hopefully I can get Aryailia to check the other links.

**Review by Aryailia — APPROVED** [review]

**Pull request merged**
